import { defineConfig }     from '../packages/core/dist/main.mjs'
import { pigeonposseTheme } from '../packages/theme/pigeonposse/dist/main.mjs'
import {
	getCurrentDir,
	getObjectFromJSONFile,
	joinPath,
	asciiFont,
} from '../packages/utils/dist/main.mjs'

const currDir      = getCurrentDir( import.meta.url )
const workspaceDir = joinPath( currDir, '..' )
const packagesDir  = joinPath( workspaceDir, 'packages' )
const coreDir      = joinPath( packagesDir, 'core' )

/** @type {import('../packages/utils/dist/main.mjs').PackageJSON}  */
const pkg = await getObjectFromJSONFile( joinPath( workspaceDir, 'package.json' ) )

/** @type {import('../packages/utils/dist/main.mjs').PackageJSON}  */
const corePkg = await getObjectFromJSONFile( joinPath( coreDir,  'package.json' ) )

export const CONSTS = {
	pkg,
	corePkg,
	workspaceDir,
	packagesDir,
	coreDir,
	mark         : `\n${asciiFont( `${pkg.extra.collective.id}\n-------\n${pkg.extra.id}`, 'ANSI Shadow' )}\n`,
	templateMark : `# Automatically generated by ${pkg.extra.id}. Please do not edit manually.`,
}

export default defineConfig(
	{
		name  : 'DOVENV WORKSPACE',
		desc  : `ToolKit for ${pkg.extra.id} repository that uses the "dovenv" core and "pigeonposse" theme.`,
		const : CONSTS,
	},
	pigeonposseTheme( {
		lint : { staged: { '**/*.{js,ts,jsx,tsx,json}': 'pnpm --silent . lint eslint --fix --silent' } },
		repo : { commit : { scopes : [
			{
				value : 'core',
				desc  : 'Core package',
			},
			{
				value : 'plugin',
				desc  : 'Plugin package(s)',
			},
			{
				value : 'theme',
				desc  : 'Theme package',
			},
			{
				value : 'utils',
				desc  : 'Utils package',
			},
			{
				value : 'all',
				desc  : 'All packages',
			},
			{
				value : 'env',
				desc  : 'Only development environment',
			},
		] } },
	} ),
)
